# Generated by Django 3.2.15 on 2023-01-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='адрес')),
                ('lat', models.FloatField(null=True, verbose_name='широта')),
                ('lon', models.FloatField(null=True, verbose_name='долгота')),
                ('query_date', models.DateField(db_index=True, verbose_name='дата запроса')),
            ],
            options={
                'verbose_name': 'местонахождение',
            },
        ),
    ]
