# Generated by Django 3.2.15 on 2023-01-31 19:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'местонахождение', 'verbose_name_plural': 'местонахождения'},
        ),
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='широта'),
        ),
        migrations.AlterField(
            model_name='location',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='долгота'),
        ),
        migrations.AlterField(
            model_name='location',
            name='query_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='дата запроса'),
        ),
    ]
