version: '3.9'

services:

  db:
    container_name: db
    image: postgres:14.6-alpine
    env_file:
      - ../.env
    volumes:
      - postgres:/var/lib/postgresql/data

  backend:
    container_name: backend
    build:
      context: ../.
      dockerfile: Dockerfile.backend
    ports:
      - '8000:8000'
    volumes:
      - ../bundles:/app/bundles
      - ../media:/app/media
      - ../staticfiles:/app/staticfiles
    env_file:
      - ../.env
    command: python /app/manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    expose:
      - 8000

volumes:
  postgres:
