# Generated by Django 3.2.15 on 2023-01-04 19:18

from django.db import migrations


def set_price(apps, schema_editor):
    OrderElement = apps.get_model('foodcartapp', 'OrderElement')
    order_element_set = OrderElement.objects.select_related(
        'product').all()
    for order_element in order_element_set.iterator():
        order_element.price = order_element.product.price \
            * order_element.quantity
        order_element.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_orderelement_price'),
    ]

    operations = [
        migrations.RunPython(set_price)
    ]
