# Generated by Django 3.2.15 on 2023-01-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_alter_orderelement_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('RA', 'Необработанный'), ('AS', 'Сборка заказа'), ('ID', 'В доставке'), ('DE', 'Доставлен')], db_index=True, default='RA', max_length=2),
        ),
    ]
