# Generated by Django 3.2.15 on 2023-01-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_auto_20230106_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('CA', 'Наличными'), ('EP', 'Электронный')], db_index=True, default='EP', max_length=2),
        ),
    ]
