# Generated by Django 3.2.15 on 2023-01-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_auto_20230125_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('CASH', 'Наличными'), ('ELECTRONIC', 'Электронный')], db_index=True, default='ELECTRONIC', max_length=15, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('RAW', 'Необработанный'), ('ASSEMBLY', 'Сборка заказа'), ('IN_DELIVERY', 'В доставке'), ('DELIVERED', 'Доставлен')], db_index=True, default='RAW', max_length=15, verbose_name='Статус заказа'),
        ),
    ]
